# Busca Cega

Abordagem de busca que não considera nenhuma informação sobre qual sucessor é mais promissor para atingir uma meta (objetivo)
###### Passos
- Formular objetivo
- Formular a busca
- Executar

### Modelando o problema
- Sliding Puzzle
<img src="images/sliding_puzzle.gif" width="250" align="center">

In [ ]:
import numpy as np

class SlidingPuzzle():
    def __init__(self, num_blocos):
        '''
        Construtor
        Args:
            - num_blocos: numero de blocos por linha e coluna, valor inteiro (Ex: 3 significa 3 linhas e 3 colunas)
        '''
        self.num_blocos = num_blocos

    def _encontra_posicao(self, estado, elemento):
        '''
        Varre todo o tabuleiro (estado) e verifica em qual posição 'elemento' está
        Args:
            - estado: matriz contendo o estado do tabuleiro
            - elemento: elemento a ser buscado na matriz
        Return:
            - Retorna a linha e coluna onde o elemento se encontra
        '''
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if estado[i, j] == elemento:
                    return i, j
        return None, None

    def verifica_estados(self, atual, objetivo):
        '''
        Verifica se o estado atual é o objetivo da busca
        Args:
            - atual: matriz que descreve o estado atual
            - objetivo: matriz que descreve o estado objetivo
        Return:
            - booleano dizendo se o estado atual é ou não o objetivo
        '''
        flag = True
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if atual[i, j] != objetivo[i, j]:
                    flag = False
                    break

        return flag

    def expande_estados(self, atual):
        '''
        Dado o estado atual, realiza a expansão de estados
        Args:
            - atual: matriz que descreve o estado atual
        Return:
            - lista com os novos estados após a expansão
        '''
        
        novos_estados = []
        linha, coluna = self._encontra_posicao(atual, 0)

        # Cima
        if linha > 0:
            novo_estado = np.copy(atual)
            nova_linha = linha - 1

            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        # Baixo
        if linha < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_linha = linha + 1

            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)


        # Esquerda
        if coluna > 0:
            novo_estado = np.copy(atual)
            nova_coluna = coluna - 1

            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        # Direita
        if coluna < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_coluna = coluna + 1

            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        return novos_estados


### Formulando Busca

#### Busca em largura (BrFS– Breadth-first search)

Realiza a busca em nível. Imagine uma árvore de estados, nela a busca é realizada sequencialmente em cada nó do mesmo nível

<img src="images/bfs.gif" width="250" align="center">

In [ ]:
from queue import Queue
# Classe 
class BreadthFirstSearch():
    
    def __init__(self, problema):
        self.problema = problema
        
    def _verifica_visitado(self, estado, estados_visitados):
        for i in estados_visitados:
            if self.problema.verifica_estados(i, estado):
                return True
        return False
        
    def busca(self, inicio, fim):
        fila = Queue()
        fila.put(inicio)
        
        solucao_encontrada = False
        estados_visitados = []
        cont_estados = 0
        
        while not fila.empty():
            atual = fila.get()
            estados_visitados.append(atual)
            
            if self.problema.verifica_estados(atual, fim):
                solucao_encontrada = True
                break
                
            else:
                cont_estados += 1
                print(f"Visitando #{cont_estados}")
                novos_estados = self.problema.expande_estados(atual)
                for i in novos_estados:
                    if not self._verifica_visitado(i, estados_visitados):
                        fila.put(i)
                        
        return solucao_encontrada, estados_visitados, cont_estados
            
## Construtor 
## Verificar se estado já foi visitado
## Busca
### Enquanto houver elementos na fila
#### Verificar objetivo
#### Expandir estados
#### Expandir estados

#### Busca em profundidade (DFS – Depth-first search)

Realiza a busca por ramo. Imagine uma árvore de estados, nela a busca é realizada sequencialmente em cada ramo, e só após completá-lo, busca no ramo vizinho.

<img src="images/dfs.gif" width="250" align="center">

In [ ]:
from queue import LifoQueue

class DepthFirstSearch():
    def __init__(self, problema):
        '''
        Construtor
        Args:
            - problema: objeto do problema a ser solucionado
        '''
        self.problema = problema
        
    def _verifica_visitado(self, estado, estados_visitados):
        '''
        Verifica se 'estado' está na lista de estados visitados
        Args:
            - estado: estado qualquer do tabuleiro
            - estados_visitados: lista com todos os estados já visitados
        Return:
            - booleano dizendo se o estado foi visitado ou não
        '''
        for i in estados_visitados:
            if self.problema.verifica_estados(i, estado):
                return True
        return False
    
    def busca(self, inicio, fim):
        '''
        Realiza a busca DFS, armazenando os estados em uma PILHA
        Args:
            - inicio: estado inicial do problema
            - fim: estado objetivo
        Return:
            - booleano se a solução foi encontrada, lista dos estados visitados, quantidade de estados visitados
        '''
        pilha = LifoQueue()
        pilha.put(inicio)
        
        solucao_encontrada = False
        estados_visitados = []
        cont_estados = 0
        
        while not pilha.empty():
            atual = pilha.get()
            estados_visitados.append(atual)
            
            if self.problema.verifica_estados(atual, fim):
                solucao_encontrada = True
                break
                
            else:
                cont_estados += 1
                print(f"Visitando #{cont_estados}")
                novos_estados = self.problema.expande_estados(atual)
                for i in novos_estados:
                    if not self._verifica_visitado(i, estados_visitados):
                        print(i)
                        pilha.put(i)
                        
        return solucao_encontrada, estados_visitados, cont_estados
    
## Construtor 
## Verificar se estado já foi visitado
## Busca
### Enquanto houver elementos na fila
#### Verificar objetivo
#### Expandir estados
#### Expandir estados

### Executando

In [ ]:
# Pacote auxiliar para o cálculo do tempo
from time import time

# Criando objeto do problema
problema = SlidingPuzzle(3)

# Criando Matriz inicial e matriz alvo
start = np.matrix([[1,0,2],[8,4,3],[7,6,5]])
target = np.matrix([[1,2,3],[8,0,4],[7,6,5]])

# Mostrando informações iniciais
print(f"Initial state: \n{start}")
print("*"*15)
print(f"Target state: \n{target}")
print("*"*15)

#### BFS

#### DFS

#### Resultados

# Exercícios

1. Alterar a matriz inicial de posições para a apresentada na imagem abaixo e avaliar a performance das duas abordagens de busca cega

<img src="images/exercicio.png" width="250" align="center">

In [9]:
# Pacote auxiliar para o cálculo do tempo
from time import time

# Criando objeto do problema
problema = SlidingPuzzle(3)

# Criando Matriz inicial e matriz alvo
start = np.matrix([[2,8,3],[1,6,4],[7,0,5]])
target = np.matrix([[1,2,3],[8,0,4],[7,6,5]])

# Mostrando informações iniciais
print(f"Initial state: \n{start}")
print("*"*15)
print(f"Target state: \n{target}")
print("*"*15)

Initial state: 
[[2 8 3]
 [1 6 4]
 [7 0 5]]
***************
Target state: 
[[1 2 3]
 [8 0 4]
 [7 6 5]]
***************


In [10]:
# Execução do BFS
bfs = BreadthFirstSearch(problema)

ini = time() # Tempo inicial

bfs_solucao, bfs_estados_visitados, bfs_num_visitados = bfs.busca(start, target) # chamando busca

bfs_time = time()-ini # Tempo total

if bfs_solucao:
    print(f"Solution found!!!")
else:
    print("Solution not found!!!")

Visitando #1
Visitando #2
Visitando #3
Visitando #4
Visitando #5
Visitando #6
Visitando #7
Visitando #8
Visitando #9
Visitando #10
Visitando #11
Visitando #12
Visitando #13
Visitando #14
Visitando #15
Visitando #16
Visitando #17
Visitando #18
Visitando #19
Visitando #20
Visitando #21
Visitando #22
Visitando #23
Visitando #24
Visitando #25
Visitando #26
Visitando #27
Visitando #28
Visitando #29
Visitando #30
Visitando #31
Visitando #32
Visitando #33
Visitando #34
Solution found!!!


In [ ]:
# Execução do DFS
dfs = DepthFirstSearch(problema)

ini = time() # Tempo inicial

dfs_solucao, dfs_estados_visitados, dfs_num_visitados = dfs.busca(start, target) # chamando busca

dfs_time = time()-ini # Tempo total

if dfs_solucao:
    print(f"Solution found!!!")
else:
    print("Solution not found!!!")

Visitando #1
[[2 8 3]
 [1 0 4]
 [7 6 5]]
[[2 8 3]
 [1 6 4]
 [0 7 5]]
[[2 8 3]
 [1 6 4]
 [7 5 0]]
Visitando #2
[[2 8 3]
 [1 6 0]
 [7 5 4]]
Visitando #3
[[2 8 0]
 [1 6 3]
 [7 5 4]]
[[2 8 3]
 [1 0 6]
 [7 5 4]]
Visitando #4
[[2 0 3]
 [1 8 6]
 [7 5 4]]
[[2 8 3]
 [1 5 6]
 [7 0 4]]
[[2 8 3]
 [0 1 6]
 [7 5 4]]
Visitando #5
[[0 8 3]
 [2 1 6]
 [7 5 4]]
[[2 8 3]
 [7 1 6]
 [0 5 4]]
Visitando #6
[[2 8 3]
 [7 1 6]
 [5 0 4]]
Visitando #7
[[2 8 3]
 [7 0 6]
 [5 1 4]]
[[2 8 3]
 [7 1 6]
 [5 4 0]]
Visitando #8
[[2 8 3]
 [7 1 0]
 [5 4 6]]
Visitando #9
[[2 8 0]
 [7 1 3]
 [5 4 6]]
[[2 8 3]
 [7 0 1]
 [5 4 6]]
Visitando #10
[[2 0 3]
 [7 8 1]
 [5 4 6]]
[[2 8 3]
 [7 4 1]
 [5 0 6]]
[[2 8 3]
 [0 7 1]
 [5 4 6]]
Visitando #11
[[0 8 3]
 [2 7 1]
 [5 4 6]]
[[2 8 3]
 [5 7 1]
 [0 4 6]]
Visitando #12
[[2 8 3]
 [5 7 1]
 [4 0 6]]
Visitando #13
[[2 8 3]
 [5 0 1]
 [4 7 6]]
[[2 8 3]
 [5 7 1]
 [4 6 0]]
Visitando #14
[[2 8 3]
 [5 7 0]
 [4 6 1]]
Visitando #15
[[2 8 0]
 [5 7 3]
 [4 6 1]]
[[2 8 3]
 [5 0 7]
 [4 6 1]]
Visitando #16
[

[[3 4 5]
 [1 0 7]
 [2 8 6]]
[[3 4 5]
 [1 8 7]
 [0 2 6]]
Visitando #155
[[3 4 5]
 [0 8 7]
 [1 2 6]]
Visitando #156
[[0 4 5]
 [3 8 7]
 [1 2 6]]
Visitando #157
[[4 0 5]
 [3 8 7]
 [1 2 6]]
Visitando #158
[[4 8 5]
 [3 0 7]
 [1 2 6]]
[[4 5 0]
 [3 8 7]
 [1 2 6]]
Visitando #159
[[4 5 7]
 [3 8 0]
 [1 2 6]]
Visitando #160
[[4 5 7]
 [3 8 6]
 [1 2 0]]
[[4 5 7]
 [3 0 8]
 [1 2 6]]
Visitando #161
[[4 0 7]
 [3 5 8]
 [1 2 6]]
[[4 5 7]
 [3 2 8]
 [1 0 6]]
[[4 5 7]
 [0 3 8]
 [1 2 6]]
Visitando #162
[[0 5 7]
 [4 3 8]
 [1 2 6]]
[[4 5 7]
 [1 3 8]
 [0 2 6]]
Visitando #163
[[4 5 7]
 [1 3 8]
 [2 0 6]]
Visitando #164
[[4 5 7]
 [1 0 8]
 [2 3 6]]
[[4 5 7]
 [1 3 8]
 [2 6 0]]
Visitando #165
[[4 5 7]
 [1 3 0]
 [2 6 8]]
Visitando #166
[[4 5 0]
 [1 3 7]
 [2 6 8]]
[[4 5 7]
 [1 0 3]
 [2 6 8]]
Visitando #167
[[4 0 7]
 [1 5 3]
 [2 6 8]]
[[4 5 7]
 [1 6 3]
 [2 0 8]]
[[4 5 7]
 [0 1 3]
 [2 6 8]]
Visitando #168
[[0 5 7]
 [4 1 3]
 [2 6 8]]
[[4 5 7]
 [2 1 3]
 [0 6 8]]
Visitando #169
[[4 5 7]
 [2 1 3]
 [6 0 8]]
Visitando #170
[[4 

[[7 6 2]
 [0 5 4]
 [1 3 8]]
Visitando #288
[[0 6 2]
 [7 5 4]
 [1 3 8]]
[[7 6 2]
 [1 5 4]
 [0 3 8]]
Visitando #289
[[7 6 2]
 [1 5 4]
 [3 0 8]]
Visitando #290
[[7 6 2]
 [1 0 4]
 [3 5 8]]
[[7 6 2]
 [1 5 4]
 [3 8 0]]
Visitando #291
[[7 6 2]
 [1 5 0]
 [3 8 4]]
Visitando #292
[[7 6 0]
 [1 5 2]
 [3 8 4]]
[[7 6 2]
 [1 0 5]
 [3 8 4]]
Visitando #293
[[7 0 2]
 [1 6 5]
 [3 8 4]]
[[7 6 2]
 [1 8 5]
 [3 0 4]]
[[7 6 2]
 [0 1 5]
 [3 8 4]]
Visitando #294
[[0 6 2]
 [7 1 5]
 [3 8 4]]
[[7 6 2]
 [3 1 5]
 [0 8 4]]
Visitando #295
[[7 6 2]
 [3 1 5]
 [8 0 4]]
Visitando #296
[[7 6 2]
 [3 0 5]
 [8 1 4]]
[[7 6 2]
 [3 1 5]
 [8 4 0]]
Visitando #297
[[7 6 2]
 [3 1 0]
 [8 4 5]]
Visitando #298
[[7 6 0]
 [3 1 2]
 [8 4 5]]
[[7 6 2]
 [3 0 1]
 [8 4 5]]
Visitando #299
[[7 0 2]
 [3 6 1]
 [8 4 5]]
[[7 6 2]
 [3 4 1]
 [8 0 5]]
[[7 6 2]
 [0 3 1]
 [8 4 5]]
Visitando #300
[[0 6 2]
 [7 3 1]
 [8 4 5]]
[[7 6 2]
 [8 3 1]
 [0 4 5]]
Visitando #301
[[7 6 2]
 [8 3 1]
 [4 0 5]]
Visitando #302
[[7 6 2]
 [8 0 1]
 [4 3 5]]
[[7 6 2]
 [8 3 1]
 

[[2 8 3]
 [4 5 1]
 [7 6 0]]
Visitando #429
[[2 8 3]
 [4 5 0]
 [7 6 1]]
Visitando #430
[[2 8 0]
 [4 5 3]
 [7 6 1]]
[[2 8 3]
 [4 0 5]
 [7 6 1]]
Visitando #431
[[2 0 3]
 [4 8 5]
 [7 6 1]]
[[2 8 3]
 [4 6 5]
 [7 0 1]]
[[2 8 3]
 [0 4 5]
 [7 6 1]]
Visitando #432
[[0 8 3]
 [2 4 5]
 [7 6 1]]
[[2 8 3]
 [7 4 5]
 [0 6 1]]
Visitando #433
[[2 8 3]
 [7 4 5]
 [6 0 1]]
Visitando #434
[[2 8 3]
 [7 0 5]
 [6 4 1]]
[[2 8 3]
 [7 4 5]
 [6 1 0]]
Visitando #435
[[2 8 3]
 [7 4 0]
 [6 1 5]]
Visitando #436
[[2 8 0]
 [7 4 3]
 [6 1 5]]
[[2 8 3]
 [7 0 4]
 [6 1 5]]
Visitando #437
[[2 0 3]
 [7 8 4]
 [6 1 5]]
[[2 8 3]
 [7 1 4]
 [6 0 5]]
[[2 8 3]
 [0 7 4]
 [6 1 5]]
Visitando #438
[[0 8 3]
 [2 7 4]
 [6 1 5]]
[[2 8 3]
 [6 7 4]
 [0 1 5]]
Visitando #439
[[2 8 3]
 [6 7 4]
 [1 0 5]]
Visitando #440
[[2 8 3]
 [6 7 4]
 [1 5 0]]
Visitando #441
Visitando #442
[[8 0 3]
 [2 7 4]
 [6 1 5]]
Visitando #443
[[8 7 3]
 [2 0 4]
 [6 1 5]]
[[8 3 0]
 [2 7 4]
 [6 1 5]]
Visitando #444
[[8 3 4]
 [2 7 0]
 [6 1 5]]
Visitando #445
[[8 3 4]
 [2 7 5]

[[4 5 1]
 [2 0 6]
 [7 8 3]]
Visitando #584
[[4 0 1]
 [2 5 6]
 [7 8 3]]
[[4 5 1]
 [2 8 6]
 [7 0 3]]
[[4 5 1]
 [0 2 6]
 [7 8 3]]
Visitando #585
[[0 5 1]
 [4 2 6]
 [7 8 3]]
[[4 5 1]
 [7 2 6]
 [0 8 3]]
Visitando #586
[[4 5 1]
 [7 2 6]
 [8 0 3]]
Visitando #587
[[4 5 1]
 [7 0 6]
 [8 2 3]]
[[4 5 1]
 [7 2 6]
 [8 3 0]]
Visitando #588
[[4 5 1]
 [7 2 0]
 [8 3 6]]
Visitando #589
[[4 5 0]
 [7 2 1]
 [8 3 6]]
[[4 5 1]
 [7 0 2]
 [8 3 6]]
Visitando #590
[[4 0 1]
 [7 5 2]
 [8 3 6]]
[[4 5 1]
 [7 3 2]
 [8 0 6]]
[[4 5 1]
 [0 7 2]
 [8 3 6]]
Visitando #591
[[0 5 1]
 [4 7 2]
 [8 3 6]]
[[4 5 1]
 [8 7 2]
 [0 3 6]]
Visitando #592
[[4 5 1]
 [8 7 2]
 [3 0 6]]
Visitando #593
[[4 5 1]
 [8 0 2]
 [3 7 6]]
[[4 5 1]
 [8 7 2]
 [3 6 0]]
Visitando #594
[[4 5 1]
 [8 7 0]
 [3 6 2]]
Visitando #595
[[4 5 0]
 [8 7 1]
 [3 6 2]]
[[4 5 1]
 [8 0 7]
 [3 6 2]]
Visitando #596
[[4 0 1]
 [8 5 7]
 [3 6 2]]
[[4 5 1]
 [8 6 7]
 [3 0 2]]
[[4 5 1]
 [0 8 7]
 [3 6 2]]
Visitando #597
[[0 5 1]
 [4 8 7]
 [3 6 2]]
[[4 5 1]
 [3 8 7]
 [0 6 2]]
Visita

Visitando #731
[[1 7 2]
 [0 8 3]
 [5 6 4]]
Visitando #732
[[0 7 2]
 [1 8 3]
 [5 6 4]]
[[1 7 2]
 [8 0 3]
 [5 6 4]]
Visitando #733
[[1 0 2]
 [8 7 3]
 [5 6 4]]
[[1 7 2]
 [8 6 3]
 [5 0 4]]
[[1 7 2]
 [8 3 0]
 [5 6 4]]
Visitando #734
[[1 7 0]
 [8 3 2]
 [5 6 4]]
[[1 7 2]
 [8 3 4]
 [5 6 0]]
Visitando #735
[[1 7 2]
 [8 3 4]
 [5 0 6]]
Visitando #736
[[1 7 2]
 [8 0 4]
 [5 3 6]]
[[1 7 2]
 [8 3 4]
 [0 5 6]]
Visitando #737
[[1 7 2]
 [0 3 4]
 [8 5 6]]
Visitando #738
[[0 7 2]
 [1 3 4]
 [8 5 6]]
[[1 7 2]
 [3 0 4]
 [8 5 6]]
Visitando #739
[[1 0 2]
 [3 7 4]
 [8 5 6]]
[[1 7 2]
 [3 5 4]
 [8 0 6]]
[[1 7 2]
 [3 4 0]
 [8 5 6]]
Visitando #740
[[1 7 0]
 [3 4 2]
 [8 5 6]]
[[1 7 2]
 [3 4 6]
 [8 5 0]]
Visitando #741
[[1 7 2]
 [3 4 6]
 [8 0 5]]
Visitando #742
[[1 7 2]
 [3 4 6]
 [0 8 5]]
Visitando #743
[[1 7 2]
 [0 4 6]
 [3 8 5]]
Visitando #744
[[0 7 2]
 [1 4 6]
 [3 8 5]]
[[1 7 2]
 [4 0 6]
 [3 8 5]]
Visitando #745
[[1 0 2]
 [4 7 6]
 [3 8 5]]
[[1 7 2]
 [4 8 6]
 [3 0 5]]
[[1 7 2]
 [4 6 0]
 [3 8 5]]
Visitando #746
[[1 

[[8 3 4]
 [0 7 2]
 [6 5 1]]
Visitando #864
[[0 3 4]
 [8 7 2]
 [6 5 1]]
[[8 3 4]
 [6 7 2]
 [0 5 1]]
Visitando #865
[[8 3 4]
 [6 7 2]
 [5 0 1]]
Visitando #866
[[8 3 4]
 [6 0 2]
 [5 7 1]]
[[8 3 4]
 [6 7 2]
 [5 1 0]]
Visitando #867
[[8 3 4]
 [6 7 0]
 [5 1 2]]
Visitando #868
[[8 3 0]
 [6 7 4]
 [5 1 2]]
[[8 3 4]
 [6 0 7]
 [5 1 2]]
Visitando #869
[[8 0 4]
 [6 3 7]
 [5 1 2]]
[[8 3 4]
 [6 1 7]
 [5 0 2]]
[[8 3 4]
 [0 6 7]
 [5 1 2]]
Visitando #870
[[0 3 4]
 [8 6 7]
 [5 1 2]]
[[8 3 4]
 [5 6 7]
 [0 1 2]]
Visitando #871
[[8 3 4]
 [5 6 7]
 [1 0 2]]
Visitando #872
[[8 3 4]
 [5 0 7]
 [1 6 2]]
[[8 3 4]
 [5 6 7]
 [1 2 0]]
Visitando #873
[[8 3 4]
 [5 6 0]
 [1 2 7]]
Visitando #874
[[8 3 0]
 [5 6 4]
 [1 2 7]]
[[8 3 4]
 [5 0 6]
 [1 2 7]]
Visitando #875
[[8 0 4]
 [5 3 6]
 [1 2 7]]
[[8 3 4]
 [5 2 6]
 [1 0 7]]
[[8 3 4]
 [0 5 6]
 [1 2 7]]
Visitando #876
[[0 3 4]
 [8 5 6]
 [1 2 7]]
[[8 3 4]
 [1 5 6]
 [0 2 7]]
Visitando #877
[[8 3 4]
 [1 5 6]
 [2 0 7]]
Visitando #878
[[8 3 4]
 [1 0 6]
 [2 5 7]]
[[8 3 4]
 [1 5 6]
 

[[4 5 6]
 [8 0 2]
 [3 1 7]]
[[4 5 6]
 [8 1 2]
 [3 7 0]]
Visitando #1005
[[4 5 6]
 [8 1 0]
 [3 7 2]]
Visitando #1006
[[4 5 0]
 [8 1 6]
 [3 7 2]]
[[4 5 6]
 [8 0 1]
 [3 7 2]]
Visitando #1007
[[4 0 6]
 [8 5 1]
 [3 7 2]]
[[4 5 6]
 [8 7 1]
 [3 0 2]]
[[4 5 6]
 [0 8 1]
 [3 7 2]]
Visitando #1008
[[0 5 6]
 [4 8 1]
 [3 7 2]]
[[4 5 6]
 [3 8 1]
 [0 7 2]]
Visitando #1009
[[4 5 6]
 [3 8 1]
 [7 0 2]]
Visitando #1010
[[4 5 6]
 [3 0 1]
 [7 8 2]]
[[4 5 6]
 [3 8 1]
 [7 2 0]]
Visitando #1011
Visitando #1012
[[4 0 6]
 [3 5 1]
 [7 8 2]]
[[4 5 6]
 [0 3 1]
 [7 8 2]]
[[4 5 6]
 [3 1 0]
 [7 8 2]]
Visitando #1013
[[4 5 0]
 [3 1 6]
 [7 8 2]]
[[4 5 6]
 [3 1 2]
 [7 8 0]]
Visitando #1014
[[4 5 6]
 [3 1 2]
 [7 0 8]]
Visitando #1015
[[4 5 6]
 [3 0 2]
 [7 1 8]]
[[4 5 6]
 [3 1 2]
 [0 7 8]]
Visitando #1016
[[4 5 6]
 [0 1 2]
 [3 7 8]]
Visitando #1017
[[0 5 6]
 [4 1 2]
 [3 7 8]]
[[4 5 6]
 [1 0 2]
 [3 7 8]]
Visitando #1018
[[4 0 6]
 [1 5 2]
 [3 7 8]]
[[4 5 6]
 [1 7 2]
 [3 0 8]]
[[4 5 6]
 [1 2 0]
 [3 7 8]]
Visitando #1019
[[4 

[[6 1 2]
 [8 0 3]
 [5 7 4]]
Visitando #1144
[[6 0 2]
 [8 1 3]
 [5 7 4]]
[[6 1 2]
 [8 7 3]
 [5 0 4]]
[[6 1 2]
 [8 3 0]
 [5 7 4]]
Visitando #1145
[[6 1 0]
 [8 3 2]
 [5 7 4]]
[[6 1 2]
 [8 3 4]
 [5 7 0]]
Visitando #1146
[[6 1 2]
 [8 3 4]
 [5 0 7]]
Visitando #1147
[[6 1 2]
 [8 0 4]
 [5 3 7]]
[[6 1 2]
 [8 3 4]
 [0 5 7]]
Visitando #1148
[[6 1 2]
 [0 3 4]
 [8 5 7]]
Visitando #1149
[[0 1 2]
 [6 3 4]
 [8 5 7]]
[[6 1 2]
 [3 0 4]
 [8 5 7]]
Visitando #1150
[[6 0 2]
 [3 1 4]
 [8 5 7]]
[[6 1 2]
 [3 5 4]
 [8 0 7]]
[[6 1 2]
 [3 4 0]
 [8 5 7]]
Visitando #1151
[[6 1 0]
 [3 4 2]
 [8 5 7]]
[[6 1 2]
 [3 4 7]
 [8 5 0]]
Visitando #1152
[[6 1 2]
 [3 4 7]
 [8 0 5]]
Visitando #1153
[[6 1 2]
 [3 4 7]
 [0 8 5]]
Visitando #1154
[[6 1 2]
 [0 4 7]
 [3 8 5]]
Visitando #1155
[[0 1 2]
 [6 4 7]
 [3 8 5]]
[[6 1 2]
 [4 0 7]
 [3 8 5]]
Visitando #1156
[[6 0 2]
 [4 1 7]
 [3 8 5]]
[[6 1 2]
 [4 8 7]
 [3 0 5]]
[[6 1 2]
 [4 7 0]
 [3 8 5]]
Visitando #1157
[[6 1 0]
 [4 7 2]
 [3 8 5]]
[[6 1 2]
 [4 7 5]
 [3 8 0]]
Visitando #1158
[[6 

[[6 0 3]
 [7 8 2]
 [5 4 1]]
[[6 8 3]
 [7 4 2]
 [5 0 1]]
[[6 8 3]
 [0 7 2]
 [5 4 1]]
Visitando #1275
[[0 8 3]
 [6 7 2]
 [5 4 1]]
[[6 8 3]
 [5 7 2]
 [0 4 1]]
Visitando #1276
[[6 8 3]
 [5 7 2]
 [4 0 1]]
Visitando #1277
[[6 8 3]
 [5 0 2]
 [4 7 1]]
[[6 8 3]
 [5 7 2]
 [4 1 0]]
Visitando #1278
[[6 8 3]
 [5 7 0]
 [4 1 2]]
Visitando #1279
[[6 8 0]
 [5 7 3]
 [4 1 2]]
[[6 8 3]
 [5 0 7]
 [4 1 2]]
Visitando #1280
[[6 0 3]
 [5 8 7]
 [4 1 2]]
[[6 8 3]
 [5 1 7]
 [4 0 2]]
[[6 8 3]
 [0 5 7]
 [4 1 2]]
Visitando #1281
[[0 8 3]
 [6 5 7]
 [4 1 2]]
[[6 8 3]
 [4 5 7]
 [0 1 2]]
Visitando #1282
[[6 8 3]
 [4 5 7]
 [1 0 2]]
Visitando #1283
[[6 8 3]
 [4 0 7]
 [1 5 2]]
[[6 8 3]
 [4 5 7]
 [1 2 0]]
Visitando #1284
[[6 8 3]
 [4 5 0]
 [1 2 7]]
Visitando #1285
[[6 8 0]
 [4 5 3]
 [1 2 7]]
[[6 8 3]
 [4 0 5]
 [1 2 7]]
Visitando #1286
[[6 0 3]
 [4 8 5]
 [1 2 7]]
[[6 8 3]
 [4 2 5]
 [1 0 7]]
[[6 8 3]
 [0 4 5]
 [1 2 7]]
Visitando #1287
[[0 8 3]
 [6 4 5]
 [1 2 7]]
[[6 8 3]
 [1 4 5]
 [0 2 7]]
Visitando #1288
[[6 8 3]
 [1 4 5]
 [

[[2 3 4]
 [5 1 6]
 [8 0 7]]
Visitando #1402
[[2 3 4]
 [5 0 6]
 [8 1 7]]
[[2 3 4]
 [5 1 6]
 [0 8 7]]
Visitando #1403
[[2 3 4]
 [0 1 6]
 [5 8 7]]
Visitando #1404
[[0 3 4]
 [2 1 6]
 [5 8 7]]
[[2 3 4]
 [1 0 6]
 [5 8 7]]
Visitando #1405
[[2 0 4]
 [1 3 6]
 [5 8 7]]
[[2 3 4]
 [1 8 6]
 [5 0 7]]
[[2 3 4]
 [1 6 0]
 [5 8 7]]
Visitando #1406
[[2 3 0]
 [1 6 4]
 [5 8 7]]
[[2 3 4]
 [1 6 7]
 [5 8 0]]
Visitando #1407
[[2 3 4]
 [1 6 7]
 [5 0 8]]
Visitando #1408
[[2 3 4]
 [1 6 7]
 [0 5 8]]
Visitando #1409
[[2 3 4]
 [0 6 7]
 [1 5 8]]
Visitando #1410
[[0 3 4]
 [2 6 7]
 [1 5 8]]
[[2 3 4]
 [6 0 7]
 [1 5 8]]
Visitando #1411
[[2 0 4]
 [6 3 7]
 [1 5 8]]
[[2 3 4]
 [6 5 7]
 [1 0 8]]
[[2 3 4]
 [6 7 0]
 [1 5 8]]
Visitando #1412
[[2 3 0]
 [6 7 4]
 [1 5 8]]
[[2 3 4]
 [6 7 8]
 [1 5 0]]
Visitando #1413
[[2 3 4]
 [6 7 8]
 [1 0 5]]
Visitando #1414
[[2 3 4]
 [6 0 8]
 [1 7 5]]
[[2 3 4]
 [6 7 8]
 [0 1 5]]
Visitando #1415
[[2 3 4]
 [0 7 8]
 [6 1 5]]
Visitando #1416
[[0 3 4]
 [2 7 8]
 [6 1 5]]
[[2 3 4]
 [7 0 8]
 [6 1 5]]
Visi

Visitando #1536
[[0 5 1]
 [4 2 7]
 [8 6 3]]
[[4 5 1]
 [2 0 7]
 [8 6 3]]
Visitando #1537
[[4 0 1]
 [2 5 7]
 [8 6 3]]
[[4 5 1]
 [2 6 7]
 [8 0 3]]
[[4 5 1]
 [2 7 0]
 [8 6 3]]
Visitando #1538
[[4 5 0]
 [2 7 1]
 [8 6 3]]
[[4 5 1]
 [2 7 3]
 [8 6 0]]
Visitando #1539
[[4 5 1]
 [2 7 3]
 [8 0 6]]
Visitando #1540
[[4 5 1]
 [2 0 3]
 [8 7 6]]
[[4 5 1]
 [2 7 3]
 [0 8 6]]
Visitando #1541
[[4 5 1]
 [0 7 3]
 [2 8 6]]
Visitando #1542
[[0 5 1]
 [4 7 3]
 [2 8 6]]
[[4 5 1]
 [7 0 3]
 [2 8 6]]
Visitando #1543
[[4 0 1]
 [7 5 3]
 [2 8 6]]
[[4 5 1]
 [7 8 3]
 [2 0 6]]
[[4 5 1]
 [7 3 0]
 [2 8 6]]
Visitando #1544
[[4 5 0]
 [7 3 1]
 [2 8 6]]
[[4 5 1]
 [7 3 6]
 [2 8 0]]
Visitando #1545
[[4 5 1]
 [7 3 6]
 [2 0 8]]
Visitando #1546
[[4 5 1]
 [7 0 6]
 [2 3 8]]
[[4 5 1]
 [7 3 6]
 [0 2 8]]
Visitando #1547
[[4 5 1]
 [0 3 6]
 [7 2 8]]
Visitando #1548
[[0 5 1]
 [4 3 6]
 [7 2 8]]
Visitando #1549
[[5 0 1]
 [4 3 6]
 [7 2 8]]
Visitando #1550
[[5 3 1]
 [4 0 6]
 [7 2 8]]
[[5 1 0]
 [4 3 6]
 [7 2 8]]
Visitando #1551
[[5 1 6]
 [4 3 0

Visitando #1673
[[1 6 8]
 [0 5 2]
 [7 4 3]]
Visitando #1674
[[0 6 8]
 [1 5 2]
 [7 4 3]]
Visitando #1675
[[6 0 8]
 [1 5 2]
 [7 4 3]]
Visitando #1676
[[6 5 8]
 [1 0 2]
 [7 4 3]]
[[6 8 0]
 [1 5 2]
 [7 4 3]]
Visitando #1677
[[6 8 2]
 [1 5 0]
 [7 4 3]]
Visitando #1678
[[6 8 2]
 [1 5 3]
 [7 4 0]]
[[6 8 2]
 [1 0 5]
 [7 4 3]]
Visitando #1679
[[6 0 2]
 [1 8 5]
 [7 4 3]]
[[6 8 2]
 [1 4 5]
 [7 0 3]]
[[6 8 2]
 [0 1 5]
 [7 4 3]]
Visitando #1680
[[0 8 2]
 [6 1 5]
 [7 4 3]]
[[6 8 2]
 [7 1 5]
 [0 4 3]]
Visitando #1681
[[6 8 2]
 [7 1 5]
 [4 0 3]]
Visitando #1682
[[6 8 2]
 [7 0 5]
 [4 1 3]]
[[6 8 2]
 [7 1 5]
 [4 3 0]]
Visitando #1683
[[6 8 2]
 [7 1 0]
 [4 3 5]]
Visitando #1684
[[6 8 0]
 [7 1 2]
 [4 3 5]]
[[6 8 2]
 [7 0 1]
 [4 3 5]]
Visitando #1685
[[6 0 2]
 [7 8 1]
 [4 3 5]]
[[6 8 2]
 [7 3 1]
 [4 0 5]]
[[6 8 2]
 [0 7 1]
 [4 3 5]]
Visitando #1686
[[0 8 2]
 [6 7 1]
 [4 3 5]]
[[6 8 2]
 [4 7 1]
 [0 3 5]]
Visitando #1687
[[6 8 2]
 [4 7 1]
 [3 0 5]]
Visitando #1688
[[6 8 2]
 [4 0 1]
 [3 7 5]]
[[6 8 2]
 [4 7 1

[[2 3 4]
 [0 8 5]
 [6 1 7]]
[[2 3 4]
 [8 5 0]
 [6 1 7]]
Visitando #1805
[[2 3 0]
 [8 5 4]
 [6 1 7]]
[[2 3 4]
 [8 5 7]
 [6 1 0]]
Visitando #1806
[[2 3 4]
 [8 5 7]
 [6 0 1]]
Visitando #1807
[[2 3 4]
 [8 0 7]
 [6 5 1]]
[[2 3 4]
 [8 5 7]
 [0 6 1]]
Visitando #1808
[[2 3 4]
 [0 5 7]
 [8 6 1]]
Visitando #1809
[[0 3 4]
 [2 5 7]
 [8 6 1]]
[[2 3 4]
 [5 0 7]
 [8 6 1]]
Visitando #1810
[[2 0 4]
 [5 3 7]
 [8 6 1]]
[[2 3 4]
 [5 6 7]
 [8 0 1]]
[[2 3 4]
 [5 7 0]
 [8 6 1]]
Visitando #1811
[[2 3 0]
 [5 7 4]
 [8 6 1]]
[[2 3 4]
 [5 7 1]
 [8 6 0]]
Visitando #1812
[[2 3 4]
 [5 7 1]
 [8 0 6]]
Visitando #1813
[[2 3 4]
 [5 7 1]
 [0 8 6]]
Visitando #1814
[[2 3 4]
 [0 7 1]
 [5 8 6]]
Visitando #1815
[[0 3 4]
 [2 7 1]
 [5 8 6]]
[[2 3 4]
 [7 0 1]
 [5 8 6]]
Visitando #1816
[[2 0 4]
 [7 3 1]
 [5 8 6]]
[[2 3 4]
 [7 8 1]
 [5 0 6]]
[[2 3 4]
 [7 1 0]
 [5 8 6]]
Visitando #1817
[[2 3 0]
 [7 1 4]
 [5 8 6]]
[[2 3 4]
 [7 1 6]
 [5 8 0]]
Visitando #1818
[[2 3 4]
 [7 1 6]
 [5 0 8]]
Visitando #1819
[[2 3 4]
 [7 1 6]
 [0 5 8]]
Visi

[[4 5 7]
 [1 8 0]
 [3 6 2]]
Visitando #1937
[[4 5 0]
 [1 8 7]
 [3 6 2]]
[[4 5 7]
 [1 8 2]
 [3 6 0]]
Visitando #1938
[[4 5 7]
 [1 8 2]
 [3 0 6]]
Visitando #1939
[[4 5 7]
 [1 0 2]
 [3 8 6]]
[[4 5 7]
 [1 8 2]
 [0 3 6]]
Visitando #1940
[[4 5 7]
 [0 8 2]
 [1 3 6]]
Visitando #1941
[[0 5 7]
 [4 8 2]
 [1 3 6]]
[[4 5 7]
 [8 0 2]
 [1 3 6]]
Visitando #1942
[[4 0 7]
 [8 5 2]
 [1 3 6]]
[[4 5 7]
 [8 3 2]
 [1 0 6]]
[[4 5 7]
 [8 2 0]
 [1 3 6]]
Visitando #1943
[[4 5 0]
 [8 2 7]
 [1 3 6]]
[[4 5 7]
 [8 2 6]
 [1 3 0]]
Visitando #1944
[[4 5 7]
 [8 2 6]
 [1 0 3]]
Visitando #1945
[[4 5 7]
 [8 2 6]
 [0 1 3]]
Visitando #1946
[[4 5 7]
 [0 2 6]
 [8 1 3]]
Visitando #1947
[[0 5 7]
 [4 2 6]
 [8 1 3]]
[[4 5 7]
 [2 0 6]
 [8 1 3]]
Visitando #1948
[[4 0 7]
 [2 5 6]
 [8 1 3]]
[[4 5 7]
 [2 1 6]
 [8 0 3]]
[[4 5 7]
 [2 6 0]
 [8 1 3]]
Visitando #1949
[[4 5 0]
 [2 6 7]
 [8 1 3]]
[[4 5 7]
 [2 6 3]
 [8 1 0]]
Visitando #1950
[[4 5 7]
 [2 6 3]
 [8 0 1]]
Visitando #1951
[[4 5 7]
 [2 0 3]
 [8 6 1]]
[[4 5 7]
 [2 6 3]
 [0 8 1]]
Visi

[[7 1 8]
 [2 6 3]
 [5 0 4]]
[[7 1 8]
 [2 3 0]
 [5 6 4]]
Visitando #2063
[[7 1 0]
 [2 3 8]
 [5 6 4]]
[[7 1 8]
 [2 3 4]
 [5 6 0]]
Visitando #2064
[[7 1 8]
 [2 3 4]
 [5 0 6]]
Visitando #2065
[[7 1 8]
 [2 0 4]
 [5 3 6]]
[[7 1 8]
 [2 3 4]
 [0 5 6]]
Visitando #2066
[[7 1 8]
 [0 3 4]
 [2 5 6]]
Visitando #2067
[[0 1 8]
 [7 3 4]
 [2 5 6]]
[[7 1 8]
 [3 0 4]
 [2 5 6]]
Visitando #2068
[[7 0 8]
 [3 1 4]
 [2 5 6]]
[[7 1 8]
 [3 5 4]
 [2 0 6]]
[[7 1 8]
 [3 4 0]
 [2 5 6]]
Visitando #2069
[[7 1 0]
 [3 4 8]
 [2 5 6]]
[[7 1 8]
 [3 4 6]
 [2 5 0]]
Visitando #2070
[[7 1 8]
 [3 4 6]
 [2 0 5]]
Visitando #2071
[[7 1 8]
 [3 4 6]
 [0 2 5]]
Visitando #2072
[[7 1 8]
 [0 4 6]
 [3 2 5]]
Visitando #2073
[[0 1 8]
 [7 4 6]
 [3 2 5]]
[[7 1 8]
 [4 0 6]
 [3 2 5]]
Visitando #2074
[[7 0 8]
 [4 1 6]
 [3 2 5]]
[[7 1 8]
 [4 2 6]
 [3 0 5]]
[[7 1 8]
 [4 6 0]
 [3 2 5]]
Visitando #2075
[[7 1 0]
 [4 6 8]
 [3 2 5]]
[[7 1 8]
 [4 6 5]
 [3 2 0]]
Visitando #2076
[[7 1 8]
 [4 6 5]
 [3 0 2]]
Visitando #2077
[[7 1 8]
 [4 0 5]
 [3 6 2]]
[[7 

[[2 3 4]
 [6 1 8]
 [5 0 7]]
Visitando #2195
[[2 3 4]
 [6 0 8]
 [5 1 7]]
[[2 3 4]
 [6 1 8]
 [5 7 0]]
Visitando #2196
[[2 3 4]
 [6 1 0]
 [5 7 8]]
Visitando #2197
[[2 3 0]
 [6 1 4]
 [5 7 8]]
[[2 3 4]
 [6 0 1]
 [5 7 8]]
Visitando #2198
[[2 0 4]
 [6 3 1]
 [5 7 8]]
[[2 3 4]
 [6 7 1]
 [5 0 8]]
[[2 3 4]
 [0 6 1]
 [5 7 8]]
Visitando #2199
[[0 3 4]
 [2 6 1]
 [5 7 8]]
[[2 3 4]
 [5 6 1]
 [0 7 8]]
Visitando #2200
[[2 3 4]
 [5 6 1]
 [7 0 8]]
Visitando #2201
[[2 3 4]
 [5 0 1]
 [7 6 8]]
[[2 3 4]
 [5 6 1]
 [7 8 0]]
Visitando #2202
[[2 3 4]
 [5 6 0]
 [7 8 1]]
Visitando #2203
[[2 3 0]
 [5 6 4]
 [7 8 1]]
[[2 3 4]
 [5 0 6]
 [7 8 1]]
Visitando #2204
[[2 0 4]
 [5 3 6]
 [7 8 1]]
[[2 3 4]
 [5 8 6]
 [7 0 1]]
[[2 3 4]
 [0 5 6]
 [7 8 1]]
Visitando #2205
[[0 3 4]
 [2 5 6]
 [7 8 1]]
[[2 3 4]
 [7 5 6]
 [0 8 1]]
Visitando #2206
[[2 3 4]
 [7 5 6]
 [8 0 1]]
Visitando #2207
[[2 3 4]
 [7 0 6]
 [8 5 1]]
[[2 3 4]
 [7 5 6]
 [8 1 0]]
Visitando #2208
[[2 3 4]
 [7 5 0]
 [8 1 6]]
Visitando #2209
[[2 3 0]
 [7 5 4]
 [8 1 6]]
[[2 

[[4 5 6]
 [2 7 8]
 [3 0 1]]
Visitando #2333
[[4 5 6]
 [2 0 8]
 [3 7 1]]
[[4 5 6]
 [2 7 8]
 [3 1 0]]
Visitando #2334
[[4 5 6]
 [2 7 0]
 [3 1 8]]
Visitando #2335
[[4 5 0]
 [2 7 6]
 [3 1 8]]
[[4 5 6]
 [2 0 7]
 [3 1 8]]
Visitando #2336
[[4 0 6]
 [2 5 7]
 [3 1 8]]
[[4 5 6]
 [2 1 7]
 [3 0 8]]
[[4 5 6]
 [0 2 7]
 [3 1 8]]
Visitando #2337
[[0 5 6]
 [4 2 7]
 [3 1 8]]
[[4 5 6]
 [3 2 7]
 [0 1 8]]
Visitando #2338
[[4 5 6]
 [3 2 7]
 [1 0 8]]
Visitando #2339
[[4 5 6]
 [3 0 7]
 [1 2 8]]
[[4 5 6]
 [3 2 7]
 [1 8 0]]
Visitando #2340
Visitando #2341
[[4 0 6]
 [3 5 7]
 [1 2 8]]
[[4 5 6]
 [0 3 7]
 [1 2 8]]
[[4 5 6]
 [3 7 0]
 [1 2 8]]
Visitando #2342
[[4 5 0]
 [3 7 6]
 [1 2 8]]
[[4 5 6]
 [3 7 8]
 [1 2 0]]
Visitando #2343
[[4 5 6]
 [3 7 8]
 [1 0 2]]
Visitando #2344
[[4 5 6]
 [3 0 8]
 [1 7 2]]
[[4 5 6]
 [3 7 8]
 [0 1 2]]
Visitando #2345
[[4 5 6]
 [0 7 8]
 [3 1 2]]
Visitando #2346
[[0 5 6]
 [4 7 8]
 [3 1 2]]
[[4 5 6]
 [7 0 8]
 [3 1 2]]
Visitando #2347
[[4 0 6]
 [7 5 8]
 [3 1 2]]
[[4 5 6]
 [7 1 8]
 [3 0 2]]
[[4 

[[6 7 8]
 [5 0 2]
 [1 4 3]]
[[6 7 8]
 [5 4 2]
 [1 3 0]]
Visitando #2466
Visitando #2467
[[6 0 8]
 [5 7 2]
 [1 4 3]]
[[6 7 8]
 [0 5 2]
 [1 4 3]]
[[6 7 8]
 [5 2 0]
 [1 4 3]]
Visitando #2468
[[6 7 0]
 [5 2 8]
 [1 4 3]]
[[6 7 8]
 [5 2 3]
 [1 4 0]]
Visitando #2469
[[6 7 8]
 [5 2 3]
 [1 0 4]]
Visitando #2470
[[6 7 8]
 [5 0 3]
 [1 2 4]]
[[6 7 8]
 [5 2 3]
 [0 1 4]]
Visitando #2471
[[6 7 8]
 [0 2 3]
 [5 1 4]]
Visitando #2472
[[0 7 8]
 [6 2 3]
 [5 1 4]]
[[6 7 8]
 [2 0 3]
 [5 1 4]]
Visitando #2473
[[6 0 8]
 [2 7 3]
 [5 1 4]]
[[6 7 8]
 [2 1 3]
 [5 0 4]]
[[6 7 8]
 [2 3 0]
 [5 1 4]]
Visitando #2474
[[6 7 0]
 [2 3 8]
 [5 1 4]]
[[6 7 8]
 [2 3 4]
 [5 1 0]]
Visitando #2475
[[6 7 8]
 [2 3 4]
 [5 0 1]]
Visitando #2476
[[6 7 8]
 [2 0 4]
 [5 3 1]]
[[6 7 8]
 [2 3 4]
 [0 5 1]]
Visitando #2477
[[6 7 8]
 [0 3 4]
 [2 5 1]]
Visitando #2478
[[0 7 8]
 [6 3 4]
 [2 5 1]]
[[6 7 8]
 [3 0 4]
 [2 5 1]]
Visitando #2479
[[6 0 8]
 [3 7 4]
 [2 5 1]]
[[6 7 8]
 [3 5 4]
 [2 0 1]]
[[6 7 8]
 [3 4 0]
 [2 5 1]]
Visitando #2480
[[6 

[[6 2 3]
 [8 7 4]
 [1 5 0]]
[[6 2 3]
 [8 0 7]
 [1 5 4]]
Visitando #2597
[[6 0 3]
 [8 2 7]
 [1 5 4]]
[[6 2 3]
 [8 5 7]
 [1 0 4]]
[[6 2 3]
 [0 8 7]
 [1 5 4]]
Visitando #2598
[[0 2 3]
 [6 8 7]
 [1 5 4]]
[[6 2 3]
 [1 8 7]
 [0 5 4]]
Visitando #2599
[[6 2 3]
 [1 8 7]
 [5 0 4]]
Visitando #2600
[[6 2 3]
 [1 0 7]
 [5 8 4]]
[[6 2 3]
 [1 8 7]
 [5 4 0]]
Visitando #2601
[[6 2 3]
 [1 8 0]
 [5 4 7]]
Visitando #2602
[[6 2 0]
 [1 8 3]
 [5 4 7]]
[[6 2 3]
 [1 0 8]
 [5 4 7]]
Visitando #2603
[[6 0 3]
 [1 2 8]
 [5 4 7]]
[[6 2 3]
 [1 4 8]
 [5 0 7]]
[[6 2 3]
 [0 1 8]
 [5 4 7]]
Visitando #2604
[[0 2 3]
 [6 1 8]
 [5 4 7]]
[[6 2 3]
 [5 1 8]
 [0 4 7]]
Visitando #2605
[[6 2 3]
 [5 1 8]
 [4 0 7]]
Visitando #2606
[[6 2 3]
 [5 0 8]
 [4 1 7]]
[[6 2 3]
 [5 1 8]
 [4 7 0]]
Visitando #2607
[[6 2 3]
 [5 1 0]
 [4 7 8]]
Visitando #2608
[[6 2 0]
 [5 1 3]
 [4 7 8]]
[[6 2 3]
 [5 0 1]
 [4 7 8]]
Visitando #2609
[[6 0 3]
 [5 2 1]
 [4 7 8]]
[[6 2 3]
 [5 7 1]
 [4 0 8]]
[[6 2 3]
 [0 5 1]
 [4 7 8]]
Visitando #2610
[[0 2 3]
 [6 5 1]
 [

[[2 3 4]
 [6 5 8]
 [0 7 1]]
Visitando #2726
[[2 3 4]
 [0 5 8]
 [6 7 1]]
Visitando #2727
[[0 3 4]
 [2 5 8]
 [6 7 1]]
[[2 3 4]
 [5 0 8]
 [6 7 1]]
Visitando #2728
[[2 0 4]
 [5 3 8]
 [6 7 1]]
[[2 3 4]
 [5 7 8]
 [6 0 1]]
[[2 3 4]
 [5 8 0]
 [6 7 1]]
Visitando #2729
[[2 3 0]
 [5 8 4]
 [6 7 1]]
[[2 3 4]
 [5 8 1]
 [6 7 0]]
Visitando #2730
[[2 3 4]
 [5 8 1]
 [6 0 7]]
Visitando #2731
[[2 3 4]
 [5 8 1]
 [0 6 7]]
Visitando #2732
[[2 3 4]
 [0 8 1]
 [5 6 7]]
Visitando #2733
[[0 3 4]
 [2 8 1]
 [5 6 7]]
[[2 3 4]
 [8 0 1]
 [5 6 7]]
Visitando #2734
[[2 0 4]
 [8 3 1]
 [5 6 7]]
[[2 3 4]
 [8 6 1]
 [5 0 7]]
[[2 3 4]
 [8 1 0]
 [5 6 7]]
Visitando #2735
[[2 3 0]
 [8 1 4]
 [5 6 7]]
[[2 3 4]
 [8 1 7]
 [5 6 0]]
Visitando #2736
[[2 3 4]
 [8 1 7]
 [5 0 6]]
Visitando #2737
[[2 3 4]
 [8 1 7]
 [0 5 6]]
Visitando #2738
[[2 3 4]
 [0 1 7]
 [8 5 6]]
Visitando #2739
[[0 3 4]
 [2 1 7]
 [8 5 6]]
[[2 3 4]
 [1 0 7]
 [8 5 6]]
Visitando #2740
[[2 0 4]
 [1 3 7]
 [8 5 6]]
[[2 3 4]
 [1 7 0]
 [8 5 6]]
Visitando #2741
[[2 3 0]
 [1 7 4

[[4 5 8]
 [7 0 6]
 [2 1 3]]
Visitando #2858
[[4 0 8]
 [7 5 6]
 [2 1 3]]
[[4 5 8]
 [7 1 6]
 [2 0 3]]
[[4 5 8]
 [0 7 6]
 [2 1 3]]
Visitando #2859
[[0 5 8]
 [4 7 6]
 [2 1 3]]
[[4 5 8]
 [2 7 6]
 [0 1 3]]
Visitando #2860
[[4 5 8]
 [2 7 6]
 [1 0 3]]
Visitando #2861
[[4 5 8]
 [2 0 6]
 [1 7 3]]
[[4 5 8]
 [2 7 6]
 [1 3 0]]
Visitando #2862
[[4 5 8]
 [2 7 0]
 [1 3 6]]
Visitando #2863
[[4 5 0]
 [2 7 8]
 [1 3 6]]
[[4 5 8]
 [2 0 7]
 [1 3 6]]
Visitando #2864
[[4 0 8]
 [2 5 7]
 [1 3 6]]
[[4 5 8]
 [2 3 7]
 [1 0 6]]
[[4 5 8]
 [0 2 7]
 [1 3 6]]
Visitando #2865
[[0 5 8]
 [4 2 7]
 [1 3 6]]
[[4 5 8]
 [1 2 7]
 [0 3 6]]
Visitando #2866
[[4 5 8]
 [1 2 7]
 [3 0 6]]
Visitando #2867
[[4 5 8]
 [1 0 7]
 [3 2 6]]
[[4 5 8]
 [1 2 7]
 [3 6 0]]
Visitando #2868
[[4 5 8]
 [1 2 0]
 [3 6 7]]
Visitando #2869
[[4 5 0]
 [1 2 8]
 [3 6 7]]
[[4 5 8]
 [1 0 2]
 [3 6 7]]
Visitando #2870
[[4 0 8]
 [1 5 2]
 [3 6 7]]
[[4 5 8]
 [1 6 2]
 [3 0 7]]
[[4 5 8]
 [0 1 2]
 [3 6 7]]
Visitando #2871
[[0 5 8]
 [4 1 2]
 [3 6 7]]
[[4 5 8]
 [3 1 2]
 [

[[8 1 0]
 [7 5 2]
 [6 3 4]]
[[8 1 2]
 [7 0 5]
 [6 3 4]]
Visitando #2984
[[8 0 2]
 [7 1 5]
 [6 3 4]]
[[8 1 2]
 [7 3 5]
 [6 0 4]]
[[8 1 2]
 [0 7 5]
 [6 3 4]]
Visitando #2985
[[0 1 2]
 [8 7 5]
 [6 3 4]]
[[8 1 2]
 [6 7 5]
 [0 3 4]]
Visitando #2986
[[8 1 2]
 [6 7 5]
 [3 0 4]]
Visitando #2987
[[8 1 2]
 [6 0 5]
 [3 7 4]]
[[8 1 2]
 [6 7 5]
 [3 4 0]]
Visitando #2988
[[8 1 2]
 [6 7 0]
 [3 4 5]]
Visitando #2989
[[8 1 0]
 [6 7 2]
 [3 4 5]]
[[8 1 2]
 [6 0 7]
 [3 4 5]]
Visitando #2990
[[8 0 2]
 [6 1 7]
 [3 4 5]]
[[8 1 2]
 [6 4 7]
 [3 0 5]]
[[8 1 2]
 [0 6 7]
 [3 4 5]]
Visitando #2991
[[0 1 2]
 [8 6 7]
 [3 4 5]]
[[8 1 2]
 [3 6 7]
 [0 4 5]]
Visitando #2992
[[8 1 2]
 [3 6 7]
 [4 0 5]]
Visitando #2993
[[8 1 2]
 [3 0 7]
 [4 6 5]]
[[8 1 2]
 [3 6 7]
 [4 5 0]]
Visitando #2994
[[8 1 2]
 [3 6 0]
 [4 5 7]]
Visitando #2995
[[8 1 0]
 [3 6 2]
 [4 5 7]]
[[8 1 2]
 [3 0 6]
 [4 5 7]]
Visitando #2996
[[8 0 2]
 [3 1 6]
 [4 5 7]]
[[8 1 2]
 [3 5 6]
 [4 0 7]]
[[8 1 2]
 [0 3 6]
 [4 5 7]]
Visitando #2997
[[0 1 2]
 [8 3 6]
 [

[[2 3 6]
 [5 7 1]
 [4 0 8]]
Visitando #3113
[[2 3 6]
 [5 0 1]
 [4 7 8]]
[[2 3 6]
 [5 7 1]
 [4 8 0]]
Visitando #3114
[[2 3 6]
 [5 7 0]
 [4 8 1]]
Visitando #3115
[[2 3 0]
 [5 7 6]
 [4 8 1]]
[[2 3 6]
 [5 0 7]
 [4 8 1]]
Visitando #3116
[[2 0 6]
 [5 3 7]
 [4 8 1]]
[[2 3 6]
 [5 8 7]
 [4 0 1]]
[[2 3 6]
 [0 5 7]
 [4 8 1]]
Visitando #3117
[[0 3 6]
 [2 5 7]
 [4 8 1]]
[[2 3 6]
 [4 5 7]
 [0 8 1]]
Visitando #3118
[[2 3 6]
 [4 5 7]
 [8 0 1]]
Visitando #3119
[[2 3 6]
 [4 0 7]
 [8 5 1]]
[[2 3 6]
 [4 5 7]
 [8 1 0]]
Visitando #3120
[[2 3 6]
 [4 5 0]
 [8 1 7]]
Visitando #3121
[[2 3 0]
 [4 5 6]
 [8 1 7]]
[[2 3 6]
 [4 0 5]
 [8 1 7]]
Visitando #3122
[[2 0 6]
 [4 3 5]
 [8 1 7]]
[[2 3 6]
 [4 1 5]
 [8 0 7]]
[[2 3 6]
 [0 4 5]
 [8 1 7]]
Visitando #3123
[[0 3 6]
 [2 4 5]
 [8 1 7]]
[[2 3 6]
 [8 4 5]
 [0 1 7]]
Visitando #3124
[[2 3 6]
 [8 4 5]
 [1 0 7]]
Visitando #3125
[[2 3 6]
 [8 0 5]
 [1 4 7]]
[[2 3 6]
 [8 4 5]
 [1 7 0]]
Visitando #3126
[[2 3 6]
 [8 4 0]
 [1 7 5]]
Visitando #3127
[[2 3 0]
 [8 4 6]
 [1 7 5]]
[[2 

Visitando #3243
[[6 4 5]
 [7 1 2]
 [8 0 3]]
Visitando #3244
[[6 4 5]
 [7 1 2]
 [0 8 3]]
Visitando #3245
[[6 4 5]
 [0 1 2]
 [7 8 3]]
Visitando #3246
[[0 4 5]
 [6 1 2]
 [7 8 3]]
[[6 4 5]
 [1 0 2]
 [7 8 3]]
Visitando #3247
[[6 0 5]
 [1 4 2]
 [7 8 3]]
[[6 4 5]
 [1 8 2]
 [7 0 3]]
[[6 4 5]
 [1 2 0]
 [7 8 3]]
Visitando #3248
[[6 4 0]
 [1 2 5]
 [7 8 3]]
[[6 4 5]
 [1 2 3]
 [7 8 0]]
Visitando #3249
[[6 4 5]
 [1 2 3]
 [7 0 8]]
Visitando #3250
[[6 4 5]
 [1 0 3]
 [7 2 8]]
[[6 4 5]
 [1 2 3]
 [0 7 8]]
Visitando #3251
[[6 4 5]
 [0 2 3]
 [1 7 8]]
Visitando #3252
[[0 4 5]
 [6 2 3]
 [1 7 8]]
[[6 4 5]
 [2 0 3]
 [1 7 8]]
Visitando #3253
[[6 0 5]
 [2 4 3]
 [1 7 8]]
[[6 4 5]
 [2 3 0]
 [1 7 8]]
Visitando #3254
[[6 4 0]
 [2 3 5]
 [1 7 8]]
[[6 4 5]
 [2 3 8]
 [1 7 0]]
Visitando #3255
[[6 4 5]
 [2 3 8]
 [1 0 7]]
Visitando #3256
[[6 4 5]
 [2 0 8]
 [1 3 7]]
[[6 4 5]
 [2 3 8]
 [0 1 7]]
Visitando #3257
[[6 4 5]
 [0 3 8]
 [2 1 7]]
Visitando #3258
[[0 4 5]
 [6 3 8]
 [2 1 7]]
Visitando #3259
[[4 0 5]
 [6 3 8]
 [2 1 7]]


[[5 8 7]
 [6 2 0]
 [3 1 4]]
Visitando #3374
[[5 8 0]
 [6 2 7]
 [3 1 4]]
[[5 8 7]
 [6 2 4]
 [3 1 0]]
Visitando #3375
[[5 8 7]
 [6 2 4]
 [3 0 1]]
Visitando #3376
[[5 8 7]
 [6 0 4]
 [3 2 1]]
[[5 8 7]
 [6 2 4]
 [0 3 1]]
Visitando #3377
[[5 8 7]
 [0 2 4]
 [6 3 1]]
Visitando #3378
[[0 8 7]
 [5 2 4]
 [6 3 1]]
[[5 8 7]
 [2 0 4]
 [6 3 1]]
Visitando #3379
[[5 0 7]
 [2 8 4]
 [6 3 1]]
[[5 8 7]
 [2 3 4]
 [6 0 1]]
[[5 8 7]
 [2 4 0]
 [6 3 1]]
Visitando #3380
[[5 8 0]
 [2 4 7]
 [6 3 1]]
[[5 8 7]
 [2 4 1]
 [6 3 0]]
Visitando #3381
[[5 8 7]
 [2 4 1]
 [6 0 3]]
Visitando #3382
[[5 8 7]
 [2 0 1]
 [6 4 3]]
[[5 8 7]
 [2 4 1]
 [0 6 3]]
Visitando #3383
[[5 8 7]
 [0 4 1]
 [2 6 3]]
Visitando #3384
[[0 8 7]
 [5 4 1]
 [2 6 3]]
Visitando #3385
[[8 0 7]
 [5 4 1]
 [2 6 3]]
Visitando #3386
[[8 4 7]
 [5 0 1]
 [2 6 3]]
[[8 7 0]
 [5 4 1]
 [2 6 3]]
Visitando #3387
[[8 7 1]
 [5 4 0]
 [2 6 3]]
Visitando #3388
[[8 7 1]
 [5 4 3]
 [2 6 0]]
[[8 7 1]
 [5 0 4]
 [2 6 3]]
Visitando #3389
[[8 0 1]
 [5 7 4]
 [2 6 3]]
[[8 7 1]
 [5 6 4

Visitando #3504
[[0 1 3]
 [7 2 8]
 [5 4 6]]
[[7 1 3]
 [2 0 8]
 [5 4 6]]
Visitando #3505
[[7 0 3]
 [2 1 8]
 [5 4 6]]
[[7 1 3]
 [2 4 8]
 [5 0 6]]
[[7 1 3]
 [2 8 0]
 [5 4 6]]
Visitando #3506
[[7 1 0]
 [2 8 3]
 [5 4 6]]
[[7 1 3]
 [2 8 6]
 [5 4 0]]
Visitando #3507
[[7 1 3]
 [2 8 6]
 [5 0 4]]
Visitando #3508
[[7 1 3]
 [2 0 6]
 [5 8 4]]
[[7 1 3]
 [2 8 6]
 [0 5 4]]
Visitando #3509
[[7 1 3]
 [0 8 6]
 [2 5 4]]
Visitando #3510
[[0 1 3]
 [7 8 6]
 [2 5 4]]
Visitando #3511
[[1 0 3]
 [7 8 6]
 [2 5 4]]
Visitando #3512
[[1 8 3]
 [7 0 6]
 [2 5 4]]
[[1 3 0]
 [7 8 6]
 [2 5 4]]
Visitando #3513
[[1 3 6]
 [7 8 0]
 [2 5 4]]
Visitando #3514
[[1 3 6]
 [7 8 4]
 [2 5 0]]
[[1 3 6]
 [7 0 8]
 [2 5 4]]
Visitando #3515
[[1 0 6]
 [7 3 8]
 [2 5 4]]
[[1 3 6]
 [7 5 8]
 [2 0 4]]
[[1 3 6]
 [0 7 8]
 [2 5 4]]
Visitando #3516
[[0 3 6]
 [1 7 8]
 [2 5 4]]
[[1 3 6]
 [2 7 8]
 [0 5 4]]
Visitando #3517
[[1 3 6]
 [2 7 8]
 [5 0 4]]
Visitando #3518
[[1 3 6]
 [2 0 8]
 [5 7 4]]
[[1 3 6]
 [2 7 8]
 [5 4 0]]
Visitando #3519
[[1 3 6]
 [2 7 0

[[6 4 5]
 [7 0 8]
 [3 1 2]]
Visitando #3635
[[6 0 5]
 [7 4 8]
 [3 1 2]]
[[6 4 5]
 [7 1 8]
 [3 0 2]]
[[6 4 5]
 [0 7 8]
 [3 1 2]]
Visitando #3636
[[0 4 5]
 [6 7 8]
 [3 1 2]]
[[6 4 5]
 [3 7 8]
 [0 1 2]]
Visitando #3637
[[6 4 5]
 [3 7 8]
 [1 0 2]]
Visitando #3638
[[6 4 5]
 [3 0 8]
 [1 7 2]]
[[6 4 5]
 [3 7 8]
 [1 2 0]]
Visitando #3639
Visitando #3640
[[6 0 5]
 [3 4 8]
 [1 7 2]]
[[6 4 5]
 [0 3 8]
 [1 7 2]]
[[6 4 5]
 [3 8 0]
 [1 7 2]]
Visitando #3641
[[6 4 0]
 [3 8 5]
 [1 7 2]]
[[6 4 5]
 [3 8 2]
 [1 7 0]]
Visitando #3642
[[6 4 5]
 [3 8 2]
 [1 0 7]]
Visitando #3643
[[6 4 5]
 [3 0 2]
 [1 8 7]]
[[6 4 5]
 [3 8 2]
 [0 1 7]]
Visitando #3644
[[6 4 5]
 [0 8 2]
 [3 1 7]]
Visitando #3645
[[0 4 5]
 [6 8 2]
 [3 1 7]]
[[6 4 5]
 [8 0 2]
 [3 1 7]]
Visitando #3646
[[6 0 5]
 [8 4 2]
 [3 1 7]]
[[6 4 5]
 [8 2 0]
 [3 1 7]]
Visitando #3647
[[6 4 0]
 [8 2 5]
 [3 1 7]]
[[6 4 5]
 [8 2 7]
 [3 1 0]]
Visitando #3648
[[6 4 5]
 [8 2 7]
 [3 0 1]]
Visitando #3649
[[6 4 5]
 [8 2 7]
 [0 3 1]]
Visitando #3650
[[6 4 5]
 [0 2 7

[[5 8 2]
 [0 4 7]
 [1 6 3]]
[[5 8 2]
 [4 7 0]
 [1 6 3]]
Visitando #3767
[[5 8 0]
 [4 7 2]
 [1 6 3]]
[[5 8 2]
 [4 7 3]
 [1 6 0]]
Visitando #3768
[[5 8 2]
 [4 7 3]
 [1 0 6]]
Visitando #3769
[[5 8 2]
 [4 0 3]
 [1 7 6]]
[[5 8 2]
 [4 7 3]
 [0 1 6]]
Visitando #3770
[[5 8 2]
 [0 7 3]
 [4 1 6]]
Visitando #3771
[[0 8 2]
 [5 7 3]
 [4 1 6]]
[[5 8 2]
 [7 0 3]
 [4 1 6]]
Visitando #3772
[[5 0 2]
 [7 8 3]
 [4 1 6]]
[[5 8 2]
 [7 1 3]
 [4 0 6]]
[[5 8 2]
 [7 3 0]
 [4 1 6]]
Visitando #3773
[[5 8 0]
 [7 3 2]
 [4 1 6]]
[[5 8 2]
 [7 3 6]
 [4 1 0]]
Visitando #3774
[[5 8 2]
 [7 3 6]
 [4 0 1]]
Visitando #3775
[[5 8 2]
 [7 0 6]
 [4 3 1]]
[[5 8 2]
 [7 3 6]
 [0 4 1]]
Visitando #3776
[[5 8 2]
 [0 3 6]
 [7 4 1]]
Visitando #3777
[[0 8 2]
 [5 3 6]
 [7 4 1]]
[[5 8 2]
 [3 0 6]
 [7 4 1]]
Visitando #3778
[[5 0 2]
 [3 8 6]
 [7 4 1]]
[[5 8 2]
 [3 4 6]
 [7 0 1]]
[[5 8 2]
 [3 6 0]
 [7 4 1]]
Visitando #3779
[[5 8 0]
 [3 6 2]
 [7 4 1]]
[[5 8 2]
 [3 6 1]
 [7 4 0]]
Visitando #3780
[[5 8 2]
 [3 6 1]
 [7 0 4]]
Visitando #3781
[[5 

[[2 7 3]
 [0 8 6]
 [1 5 4]]
[[2 7 3]
 [8 6 0]
 [1 5 4]]
Visitando #3893
[[2 7 0]
 [8 6 3]
 [1 5 4]]
[[2 7 3]
 [8 6 4]
 [1 5 0]]
Visitando #3894
[[2 7 3]
 [8 6 4]
 [1 0 5]]
Visitando #3895
[[2 7 3]
 [8 0 4]
 [1 6 5]]
[[2 7 3]
 [8 6 4]
 [0 1 5]]
Visitando #3896
[[2 7 3]
 [0 6 4]
 [8 1 5]]
Visitando #3897
[[0 7 3]
 [2 6 4]
 [8 1 5]]
[[2 7 3]
 [6 0 4]
 [8 1 5]]
Visitando #3898
[[2 0 3]
 [6 7 4]
 [8 1 5]]
[[2 7 3]
 [6 1 4]
 [8 0 5]]
[[2 7 3]
 [6 4 0]
 [8 1 5]]
Visitando #3899
[[2 7 0]
 [6 4 3]
 [8 1 5]]
[[2 7 3]
 [6 4 5]
 [8 1 0]]
Visitando #3900
[[2 7 3]
 [6 4 5]
 [8 0 1]]
Visitando #3901
[[2 7 3]
 [6 0 5]
 [8 4 1]]
[[2 7 3]
 [6 4 5]
 [0 8 1]]
Visitando #3902
[[2 7 3]
 [0 4 5]
 [6 8 1]]
Visitando #3903
[[0 7 3]
 [2 4 5]
 [6 8 1]]
[[2 7 3]
 [4 0 5]
 [6 8 1]]
Visitando #3904
[[2 0 3]
 [4 7 5]
 [6 8 1]]
[[2 7 3]
 [4 8 5]
 [6 0 1]]
[[2 7 3]
 [4 5 0]
 [6 8 1]]
Visitando #3905
[[2 7 0]
 [4 5 3]
 [6 8 1]]
[[2 7 3]
 [4 5 1]
 [6 8 0]]
Visitando #3906
[[2 7 3]
 [4 5 1]
 [6 0 8]]
Visitando #3907
[[2 

[[2 6 4]
 [0 3 7]
 [1 8 5]]
Visitando #4023
[[0 6 4]
 [2 3 7]
 [1 8 5]]
[[2 6 4]
 [1 3 7]
 [0 8 5]]
Visitando #4024
[[2 6 4]
 [1 3 7]
 [8 0 5]]
Visitando #4025
[[2 6 4]
 [1 0 7]
 [8 3 5]]
[[2 6 4]
 [1 3 7]
 [8 5 0]]
Visitando #4026
[[2 6 4]
 [1 3 0]
 [8 5 7]]
Visitando #4027
[[2 6 0]
 [1 3 4]
 [8 5 7]]
[[2 6 4]
 [1 0 3]
 [8 5 7]]
Visitando #4028
[[2 0 4]
 [1 6 3]
 [8 5 7]]
[[2 6 4]
 [1 5 3]
 [8 0 7]]
[[2 6 4]
 [0 1 3]
 [8 5 7]]
Visitando #4029
[[0 6 4]
 [2 1 3]
 [8 5 7]]
[[2 6 4]
 [8 1 3]
 [0 5 7]]
Visitando #4030
[[2 6 4]
 [8 1 3]
 [5 0 7]]
Visitando #4031
[[2 6 4]
 [8 0 3]
 [5 1 7]]
[[2 6 4]
 [8 1 3]
 [5 7 0]]
Visitando #4032
[[2 6 4]
 [8 1 0]
 [5 7 3]]
Visitando #4033
[[2 6 0]
 [8 1 4]
 [5 7 3]]
[[2 6 4]
 [8 0 1]
 [5 7 3]]
Visitando #4034
[[2 0 4]
 [8 6 1]
 [5 7 3]]
[[2 6 4]
 [8 7 1]
 [5 0 3]]
[[2 6 4]
 [0 8 1]
 [5 7 3]]
Visitando #4035
[[0 6 4]
 [2 8 1]
 [5 7 3]]
[[2 6 4]
 [5 8 1]
 [0 7 3]]
Visitando #4036
[[2 6 4]
 [5 8 1]
 [7 0 3]]
Visitando #4037
[[2 6 4]
 [5 0 1]
 [7 8 3]]
[[2 

Visitando #4152
[[0 4 5]
 [2 3 6]
 [1 7 8]]
[[2 4 5]
 [1 3 6]
 [0 7 8]]
Visitando #4153
[[2 4 5]
 [1 3 6]
 [7 0 8]]
Visitando #4154
[[2 4 5]
 [1 0 6]
 [7 3 8]]
[[2 4 5]
 [1 3 6]
 [7 8 0]]
Visitando #4155
[[2 4 5]
 [1 3 0]
 [7 8 6]]
Visitando #4156
[[2 4 0]
 [1 3 5]
 [7 8 6]]
[[2 4 5]
 [1 0 3]
 [7 8 6]]
Visitando #4157
[[2 0 5]
 [1 4 3]
 [7 8 6]]
[[2 4 5]
 [1 8 3]
 [7 0 6]]
[[2 4 5]
 [0 1 3]
 [7 8 6]]
Visitando #4158
[[0 4 5]
 [2 1 3]
 [7 8 6]]
[[2 4 5]
 [7 1 3]
 [0 8 6]]
Visitando #4159
[[2 4 5]
 [7 1 3]
 [8 0 6]]
Visitando #4160
[[2 4 5]
 [7 0 3]
 [8 1 6]]
[[2 4 5]
 [7 1 3]
 [8 6 0]]
Visitando #4161
[[2 4 5]
 [7 1 0]
 [8 6 3]]
Visitando #4162
[[2 4 0]
 [7 1 5]
 [8 6 3]]
[[2 4 5]
 [7 0 1]
 [8 6 3]]
Visitando #4163
[[2 0 5]
 [7 4 1]
 [8 6 3]]
[[2 4 5]
 [7 6 1]
 [8 0 3]]
[[2 4 5]
 [0 7 1]
 [8 6 3]]
Visitando #4164
[[0 4 5]
 [2 7 1]
 [8 6 3]]
[[2 4 5]
 [8 7 1]
 [0 6 3]]
Visitando #4165
[[2 4 5]
 [8 7 1]
 [6 0 3]]
Visitando #4166
[[2 4 5]
 [8 0 1]
 [6 7 3]]
[[2 4 5]
 [8 7 1]
 [6 3 0]]
Visi

Visitando #4278
[[3 5 8]
 [4 7 6]
 [1 0 2]]
Visitando #4279
[[3 5 8]
 [4 0 6]
 [1 7 2]]
[[3 5 8]
 [4 7 6]
 [0 1 2]]
Visitando #4280
[[3 5 8]
 [0 7 6]
 [4 1 2]]
Visitando #4281
[[0 5 8]
 [3 7 6]
 [4 1 2]]
[[3 5 8]
 [7 0 6]
 [4 1 2]]
Visitando #4282
[[3 0 8]
 [7 5 6]
 [4 1 2]]
[[3 5 8]
 [7 1 6]
 [4 0 2]]
[[3 5 8]
 [7 6 0]
 [4 1 2]]
Visitando #4283
[[3 5 0]
 [7 6 8]
 [4 1 2]]
[[3 5 8]
 [7 6 2]
 [4 1 0]]
Visitando #4284
[[3 5 8]
 [7 6 2]
 [4 0 1]]
Visitando #4285
[[3 5 8]
 [7 0 2]
 [4 6 1]]
[[3 5 8]
 [7 6 2]
 [0 4 1]]
Visitando #4286
[[3 5 8]
 [0 6 2]
 [7 4 1]]
Visitando #4287
[[0 5 8]
 [3 6 2]
 [7 4 1]]
[[3 5 8]
 [6 0 2]
 [7 4 1]]
Visitando #4288
[[3 0 8]
 [6 5 2]
 [7 4 1]]
[[3 5 8]
 [6 4 2]
 [7 0 1]]
[[3 5 8]
 [6 2 0]
 [7 4 1]]
Visitando #4289
[[3 5 0]
 [6 2 8]
 [7 4 1]]
[[3 5 8]
 [6 2 1]
 [7 4 0]]
Visitando #4290
[[3 5 8]
 [6 2 1]
 [7 0 4]]
Visitando #4291
[[3 5 8]
 [6 2 1]
 [0 7 4]]
Visitando #4292
[[3 5 8]
 [0 2 1]
 [6 7 4]]
Visitando #4293
[[0 5 8]
 [3 2 1]
 [6 7 4]]
[[3 5 8]
 [2 0 1

[[7 6 2]
 [3 8 0]
 [4 1 5]]
Visitando #4411
[[7 6 0]
 [3 8 2]
 [4 1 5]]
[[7 6 2]
 [3 0 8]
 [4 1 5]]
Visitando #4412
[[7 0 2]
 [3 6 8]
 [4 1 5]]
[[7 6 2]
 [3 1 8]
 [4 0 5]]
[[7 6 2]
 [0 3 8]
 [4 1 5]]
Visitando #4413
[[0 6 2]
 [7 3 8]
 [4 1 5]]
[[7 6 2]
 [4 3 8]
 [0 1 5]]
Visitando #4414
[[7 6 2]
 [4 3 8]
 [1 0 5]]
Visitando #4415
[[7 6 2]
 [4 0 8]
 [1 3 5]]
[[7 6 2]
 [4 3 8]
 [1 5 0]]
Visitando #4416
[[7 6 2]
 [4 3 0]
 [1 5 8]]
Visitando #4417
[[7 6 0]
 [4 3 2]
 [1 5 8]]
[[7 6 2]
 [4 0 3]
 [1 5 8]]
Visitando #4418
[[7 0 2]
 [4 6 3]
 [1 5 8]]
[[7 6 2]
 [4 5 3]
 [1 0 8]]
[[7 6 2]
 [0 4 3]
 [1 5 8]]
Visitando #4419
[[0 6 2]
 [7 4 3]
 [1 5 8]]
[[7 6 2]
 [1 4 3]
 [0 5 8]]
Visitando #4420
[[7 6 2]
 [1 4 3]
 [5 0 8]]
Visitando #4421
[[7 6 2]
 [1 0 3]
 [5 4 8]]
[[7 6 2]
 [1 4 3]
 [5 8 0]]
Visitando #4422
[[7 6 2]
 [1 4 0]
 [5 8 3]]
Visitando #4423
[[7 6 0]
 [1 4 2]
 [5 8 3]]
[[7 6 2]
 [1 0 4]
 [5 8 3]]
Visitando #4424
[[7 0 2]
 [1 6 4]
 [5 8 3]]
[[7 6 2]
 [1 8 4]
 [5 0 3]]
[[7 6 2]
 [0 1 4]
 [

Visitando #4539
[[0 1 4]
 [2 3 6]
 [8 5 7]]
[[2 1 4]
 [8 3 6]
 [0 5 7]]
Visitando #4540
[[2 1 4]
 [8 3 6]
 [5 0 7]]
Visitando #4541
[[2 1 4]
 [8 0 6]
 [5 3 7]]
[[2 1 4]
 [8 3 6]
 [5 7 0]]
Visitando #4542
[[2 1 4]
 [8 3 0]
 [5 7 6]]
Visitando #4543
[[2 1 0]
 [8 3 4]
 [5 7 6]]
[[2 1 4]
 [8 0 3]
 [5 7 6]]
Visitando #4544
[[2 0 4]
 [8 1 3]
 [5 7 6]]
[[2 1 4]
 [8 7 3]
 [5 0 6]]
[[2 1 4]
 [0 8 3]
 [5 7 6]]
Visitando #4545
[[0 1 4]
 [2 8 3]
 [5 7 6]]
[[2 1 4]
 [5 8 3]
 [0 7 6]]
Visitando #4546
[[2 1 4]
 [5 8 3]
 [7 0 6]]
Visitando #4547
[[2 1 4]
 [5 0 3]
 [7 8 6]]
[[2 1 4]
 [5 8 3]
 [7 6 0]]
Visitando #4548
[[2 1 4]
 [5 8 0]
 [7 6 3]]
Visitando #4549
[[2 1 0]
 [5 8 4]
 [7 6 3]]
[[2 1 4]
 [5 0 8]
 [7 6 3]]
Visitando #4550
[[2 0 4]
 [5 1 8]
 [7 6 3]]
[[2 1 4]
 [5 6 8]
 [7 0 3]]
[[2 1 4]
 [0 5 8]
 [7 6 3]]
Visitando #4551
[[0 1 4]
 [2 5 8]
 [7 6 3]]
[[2 1 4]
 [7 5 8]
 [0 6 3]]
Visitando #4552
[[2 1 4]
 [7 5 8]
 [6 0 3]]
Visitando #4553
[[2 1 4]
 [7 0 8]
 [6 5 3]]
[[2 1 4]
 [7 5 8]
 [6 3 0]]
Visi

[[4 2 5]
 [8 0 6]
 [1 7 3]]
[[4 2 5]
 [8 7 6]
 [0 1 3]]
Visitando #4667
[[4 2 5]
 [0 7 6]
 [8 1 3]]
Visitando #4668
[[0 2 5]
 [4 7 6]
 [8 1 3]]
[[4 2 5]
 [7 0 6]
 [8 1 3]]
Visitando #4669
[[4 0 5]
 [7 2 6]
 [8 1 3]]
[[4 2 5]
 [7 1 6]
 [8 0 3]]
[[4 2 5]
 [7 6 0]
 [8 1 3]]
Visitando #4670
[[4 2 0]
 [7 6 5]
 [8 1 3]]
[[4 2 5]
 [7 6 3]
 [8 1 0]]
Visitando #4671
[[4 2 5]
 [7 6 3]
 [8 0 1]]
Visitando #4672
[[4 2 5]
 [7 0 3]
 [8 6 1]]
[[4 2 5]
 [7 6 3]
 [0 8 1]]
Visitando #4673
[[4 2 5]
 [0 6 3]
 [7 8 1]]
Visitando #4674
[[0 2 5]
 [4 6 3]
 [7 8 1]]
[[4 2 5]
 [6 0 3]
 [7 8 1]]
Visitando #4675
[[4 0 5]
 [6 2 3]
 [7 8 1]]
[[4 2 5]
 [6 8 3]
 [7 0 1]]
[[4 2 5]
 [6 3 0]
 [7 8 1]]
Visitando #4676
[[4 2 0]
 [6 3 5]
 [7 8 1]]
[[4 2 5]
 [6 3 1]
 [7 8 0]]
Visitando #4677
[[4 2 5]
 [6 3 1]
 [7 0 8]]
Visitando #4678
[[4 2 5]
 [6 0 1]
 [7 3 8]]
[[4 2 5]
 [6 3 1]
 [0 7 8]]
Visitando #4679
[[4 2 5]
 [0 3 1]
 [6 7 8]]
Visitando #4680
[[0 2 5]
 [4 3 1]
 [6 7 8]]
[[4 2 5]
 [3 0 1]
 [6 7 8]]
Visitando #4681
[[4 

[[4 8 7]
 [1 3 5]
 [0 6 2]]
Visitando #4795
[[4 8 7]
 [1 3 5]
 [6 0 2]]
Visitando #4796
[[4 8 7]
 [1 0 5]
 [6 3 2]]
[[4 8 7]
 [1 3 5]
 [6 2 0]]
Visitando #4797
[[4 8 7]
 [1 3 0]
 [6 2 5]]
Visitando #4798
[[4 8 0]
 [1 3 7]
 [6 2 5]]
[[4 8 7]
 [1 0 3]
 [6 2 5]]
Visitando #4799
[[4 0 7]
 [1 8 3]
 [6 2 5]]
[[4 8 7]
 [1 2 3]
 [6 0 5]]
[[4 8 7]
 [0 1 3]
 [6 2 5]]
Visitando #4800
[[0 8 7]
 [4 1 3]
 [6 2 5]]
[[4 8 7]
 [6 1 3]
 [0 2 5]]
Visitando #4801
[[4 8 7]
 [6 1 3]
 [2 0 5]]
Visitando #4802
[[4 8 7]
 [6 0 3]
 [2 1 5]]
[[4 8 7]
 [6 1 3]
 [2 5 0]]
Visitando #4803
[[4 8 7]
 [6 1 0]
 [2 5 3]]
Visitando #4804
[[4 8 0]
 [6 1 7]
 [2 5 3]]
[[4 8 7]
 [6 0 1]
 [2 5 3]]
Visitando #4805
[[4 0 7]
 [6 8 1]
 [2 5 3]]
[[4 8 7]
 [6 5 1]
 [2 0 3]]
[[4 8 7]
 [0 6 1]
 [2 5 3]]
Visitando #4806
[[0 8 7]
 [4 6 1]
 [2 5 3]]
[[4 8 7]
 [2 6 1]
 [0 5 3]]
Visitando #4807
[[4 8 7]
 [2 6 1]
 [5 0 3]]
Visitando #4808
[[4 8 7]
 [2 0 1]
 [5 6 3]]
[[4 8 7]
 [2 6 1]
 [5 3 0]]
Visitando #4809
[[4 8 7]
 [2 6 0]
 [5 3 1]]
Visi

[[7 6 1]
 [5 3 8]
 [2 0 4]]
Visitando #4922
[[7 6 1]
 [5 0 8]
 [2 3 4]]
[[7 6 1]
 [5 3 8]
 [2 4 0]]
Visitando #4923
[[7 6 1]
 [5 3 0]
 [2 4 8]]
Visitando #4924
[[7 6 0]
 [5 3 1]
 [2 4 8]]
[[7 6 1]
 [5 0 3]
 [2 4 8]]
Visitando #4925
[[7 0 1]
 [5 6 3]
 [2 4 8]]
[[7 6 1]
 [5 4 3]
 [2 0 8]]
[[7 6 1]
 [0 5 3]
 [2 4 8]]
Visitando #4926
[[0 6 1]
 [7 5 3]
 [2 4 8]]
[[7 6 1]
 [2 5 3]
 [0 4 8]]
Visitando #4927
[[7 6 1]
 [2 5 3]
 [4 0 8]]
Visitando #4928
[[7 6 1]
 [2 0 3]
 [4 5 8]]
[[7 6 1]
 [2 5 3]
 [4 8 0]]
Visitando #4929
[[7 6 1]
 [2 5 0]
 [4 8 3]]
Visitando #4930
[[7 6 0]
 [2 5 1]
 [4 8 3]]
[[7 6 1]
 [2 0 5]
 [4 8 3]]
Visitando #4931
[[7 0 1]
 [2 6 5]
 [4 8 3]]
[[7 6 1]
 [2 8 5]
 [4 0 3]]
[[7 6 1]
 [0 2 5]
 [4 8 3]]
Visitando #4932
[[0 6 1]
 [7 2 5]
 [4 8 3]]
[[7 6 1]
 [4 2 5]
 [0 8 3]]
Visitando #4933
[[7 6 1]
 [4 2 5]
 [8 0 3]]
Visitando #4934
[[7 6 1]
 [4 0 5]
 [8 2 3]]
[[7 6 1]
 [4 2 5]
 [8 3 0]]
Visitando #4935
[[7 6 1]
 [4 2 0]
 [8 3 5]]
Visitando #4936
[[7 6 0]
 [4 2 1]
 [8 3 5]]
[[7 

Visitando #5048
[[1 2 5]
 [0 3 8]
 [4 6 7]]
Visitando #5049
[[0 2 5]
 [1 3 8]
 [4 6 7]]
[[1 2 5]
 [3 0 8]
 [4 6 7]]
Visitando #5050
[[1 0 5]
 [3 2 8]
 [4 6 7]]
[[1 2 5]
 [3 6 8]
 [4 0 7]]
[[1 2 5]
 [3 8 0]
 [4 6 7]]
Visitando #5051
[[1 2 0]
 [3 8 5]
 [4 6 7]]
[[1 2 5]
 [3 8 7]
 [4 6 0]]
Visitando #5052
[[1 2 5]
 [3 8 7]
 [4 0 6]]
Visitando #5053
[[1 2 5]
 [3 8 7]
 [0 4 6]]
Visitando #5054
[[1 2 5]
 [0 8 7]
 [3 4 6]]
Visitando #5055
[[0 2 5]
 [1 8 7]
 [3 4 6]]
[[1 2 5]
 [8 0 7]
 [3 4 6]]
Visitando #5056
[[1 0 5]
 [8 2 7]
 [3 4 6]]
[[1 2 5]
 [8 4 7]
 [3 0 6]]
[[1 2 5]
 [8 7 0]
 [3 4 6]]
Visitando #5057
[[1 2 0]
 [8 7 5]
 [3 4 6]]
[[1 2 5]
 [8 7 6]
 [3 4 0]]
Visitando #5058
[[1 2 5]
 [8 7 6]
 [3 0 4]]
Visitando #5059
[[1 2 5]
 [8 0 6]
 [3 7 4]]
[[1 2 5]
 [8 7 6]
 [0 3 4]]
Visitando #5060
[[1 2 5]
 [0 7 6]
 [8 3 4]]
Visitando #5061
[[0 2 5]
 [1 7 6]
 [8 3 4]]
[[1 2 5]
 [7 0 6]
 [8 3 4]]
Visitando #5062
[[1 0 5]
 [7 2 6]
 [8 3 4]]
[[1 2 5]
 [7 3 6]
 [8 0 4]]
[[1 2 5]
 [7 6 0]
 [8 3 4]]
Visi

[[5 4 3]
 [0 6 1]
 [8 2 7]]
Visitando #5175
[[0 4 3]
 [5 6 1]
 [8 2 7]]
[[5 4 3]
 [6 0 1]
 [8 2 7]]
Visitando #5176
[[5 0 3]
 [6 4 1]
 [8 2 7]]
[[5 4 3]
 [6 2 1]
 [8 0 7]]
[[5 4 3]
 [6 1 0]
 [8 2 7]]
Visitando #5177
[[5 4 0]
 [6 1 3]
 [8 2 7]]
[[5 4 3]
 [6 1 7]
 [8 2 0]]
Visitando #5178
[[5 4 3]
 [6 1 7]
 [8 0 2]]
Visitando #5179
[[5 4 3]
 [6 1 7]
 [0 8 2]]
Visitando #5180
[[5 4 3]
 [0 1 7]
 [6 8 2]]
Visitando #5181
[[0 4 3]
 [5 1 7]
 [6 8 2]]
[[5 4 3]
 [1 0 7]
 [6 8 2]]
Visitando #5182
[[5 0 3]
 [1 4 7]
 [6 8 2]]
[[5 4 3]
 [1 8 7]
 [6 0 2]]
[[5 4 3]
 [1 7 0]
 [6 8 2]]
Visitando #5183
[[5 4 0]
 [1 7 3]
 [6 8 2]]
[[5 4 3]
 [1 7 2]
 [6 8 0]]
Visitando #5184
[[5 4 3]
 [1 7 2]
 [6 0 8]]
Visitando #5185
[[5 4 3]
 [1 0 2]
 [6 7 8]]
[[5 4 3]
 [1 7 2]
 [0 6 8]]
Visitando #5186
[[5 4 3]
 [0 7 2]
 [1 6 8]]
Visitando #5187
[[0 4 3]
 [5 7 2]
 [1 6 8]]
[[5 4 3]
 [7 0 2]
 [1 6 8]]
Visitando #5188
[[5 0 3]
 [7 4 2]
 [1 6 8]]
[[5 4 3]
 [7 6 2]
 [1 0 8]]
[[5 4 3]
 [7 2 0]
 [1 6 8]]
Visitando #5189
[[5 

2. Desenhe no papel, a árvore dos seguintes grafos e diga qual o caminho BFS e DFS saindo de O e indo para X.

A)

<img src="images/GRAFO_A.png" width="250" align="center">

B)

<img src="images/GRAFO_B.png" width="250" align="center">

In [ ]:
# Pacote auxiliar para o cálculo do tempo
from time import time

# Criando objeto do problema
problema = SlidingPuzzle(3)

# Criando Matriz inicial e matriz alvo
start = np.matrix([[2,8,3],[1,6,4],[7,0,5]])
target = np.matrix([[1,2,3],[8,0,4],[7,6,5]])

# Mostrando informações iniciais
print(f"Initial state: \n{start}")
print("*"*15)
print(f"Target state: \n{target}")
print("*"*15)